# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 🚀Deploy DevIcon in EC2 hml

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    name: ▶️ Start Build
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - uses: actions/checkout@v3
    - name: 🔧 Cerating Enviroment and install dependencies
      run: |
        cd /home/ubuntu/app/

        python -m venv venv
        source venv/bin/activate

        cd /home/ubuntu/actions-runner/_work/devicons/devicons

        pip install -r requirements.txt  

    - name: 🗑️ Remove all config files
      run: |
        sudo systemctl stop nginx
         sudo rm -rf /etc/nginx/sites-available/default
         sudo rm -rf /etc/nginx/sites-enabled/default
         sudo rm -rf /etc/systemd/system/devicon.service

    - name: 🐣Run DevIcon
      run: |
        sudo mv /home/ubuntu/actions-runner/_work/devicons/devicons/conf/devicon.service /etc/systemd/system/
        sudo systemctl daemon-reload
        sudo systemctl start devicon
        sudo systemctl restart devicon

    - name: 🆖 Run Nginx
      run: |
        sudo systemctl restart nginx

    
            
